import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import auditoriumIMG from "../images/clasroom.jpg";
import e1 from "../images/e1.jpg";
import e2 from "../images/e2.jpg";
import e3 from "../images/e3.jpg";
import e4 from "../images/e4.jpg";
import e5 from "../images/e5.jpg";
import e6 from "../images/e6.jpg";
import e7 from "../images/e7.jpg";
import maturityIMG from "../images/maturity.png";
import iveriaIMG from "../images/iveria.jpg";
import mapSameba from "../images/map_sameba.jpg";
import iconByz from "../images/icon_byz.png";
import calendarIMG from "../images/calendar.png";
import sazuIMG from "../images/sazu.png";
import { useState, useEffect } from "react";

function formatTextWithRedTime(text) {
  if (!text) return null;
  const timeRegex = /(\d{1,2}:\d{2})/g;
  const formattedText = text.replace(
    timeRegex,
    '<span style="color: red; font-weight: 600;">$1</span>'
  );
  return <span dangerouslySetInnerHTML={{ __html: formattedText }} />;
}

export default function Home({ data = {} }) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [expandedDays, setExpandedDays] = useState([]);
  const images = [e1, e2, e3, e4, e5, e6, e7];
  const {
    scheduleData = [],
    auditoriumData = [],
    videoData = [],
    blogData = [],
  } = data;

  const scheduleMap = scheduleData.reduce((acc, day) => {
    acc[day.day_name] = {
      text: `${day.event_description || ""} ${day.event_time || ""}`.trim(),
      updated: day.updated_formatted,
    };
    return acc;
  }, {});

  const auditoriumInfo = auditoriumData[0] || {};
  const toggleExpand = (dayKey) => {
    setExpandedDays((prev) =>
      prev.includes(dayKey)
        ? prev.filter((key) => key !== dayKey)
        : [...prev, dayKey]
    );
  };
  const dayNamesMap = {
    ორშაბათი: { name: "ორშაბათი", key: "wk1" },
    სამშაბათი: { name: "სამშაბათი", key: "wk2" },
    ოთხშაბათი: { name: "ოთხშაბათი", key: "wk3" },
    ხუთშაბათი: { name: "ხუთშაბათი", key: "wk4" },
    პარასკევი: { name: "პარასკევი", key: "wk5" },
    შაბათი: { name: "შაბათი", key: "wk6" },
    კვირა: { name: "კვირა", key: "wk7" },
  };
  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentSlide((prevSlide) => (prevSlide + 1) % images.length);
    }, 8000);
    return () => clearInterval(timer);
  }, [images.length]);
  const goToSlide = (index) => setCurrentSlide(index);

  return (
    <>
      <Head>
        <title>ივერიის ღვთისმშობლის ტაძარი</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.angelOverlay}>
          <div className={styles.leftAngel}></div>
          <div className={styles.rightAngel}></div>
        </div>
        <div className={styles.contentWrapper}>
          <div className={styles.headerTitle}>ივერიის ღვთისმშობლის ტაძარი</div>
          <div className={styles.week_calendar}>
            <div className={styles.week_calendar_vineyard}></div>
            <div className={styles.week_calendar_vineyard_right}></div>
            <div className={styles.week_calendar_inner}>
              {[
                ["ორშაბათი", "სამშაბათი", "ოთხშაბათი"],
                ["ხუთშაბათი", "პარასკევი", "შაბათი"],
              ].map((column, colIndex) => (
                <div
                  key={colIndex}
                  className={`${styles.week_day} ${
                    colIndex === 0 ? styles.leftColumn : styles.rightColumn
                  }`}
                >
                  {column.map((dayName) => {
                    const dayInfo = dayNamesMap[dayName];
                    const scheduleItem = scheduleMap[dayName];
                    // განსაზღვრეთ order ატრიბუტი
                    let order;
                    if (dayName === "ორშაბათი") order = 1;
                    if (dayName === "სამშაბათი") order = 2;
                    if (dayName === "ოთხშაბათი") order = 3;
                    if (dayName === "ხუთშაბათი") order = 5;
                    if (dayName === "პარასკევი") order = 6;
                    if (dayName === "შაბათი") order = 7;
                    return (
                      <div
                        key={dayInfo.key}
                        className={styles.week_day_item}
                        data-day-order={order}
                      >
                        <h1 onClick={() => toggleExpand(dayInfo.key)}>
                          {dayInfo.name}
                        </h1>
                        <div
                          className={`${styles.week_day_text} ${
                            expandedDays.includes(dayInfo.key)
                              ? styles.expanded
                              : ""
                          }`}
                        >
                          <p>{formatTextWithRedTime(scheduleItem?.text)}</p>
                          {scheduleItem?.updated && (
                            <small className={styles.updated_date}>
                              განახლდა: {scheduleItem.updated}
                            </small>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              ))}
              <div className={styles.iveria_image} data-day-order="4">
                <Image
                  src={iveriaIMG}
                  alt="Iveria Icon"
                  width={200}
                  height={300}
                  loading="lazy"
                  className={styles.rounded_image}
                />
              </div>
              <div
                className={`${styles.week_day} ${styles.bottomRow}`}
                data-day-order="8"
              >
                <div className={styles.week_day_item}>
                  <h1 onClick={() => toggleExpand(dayNamesMap["კვირა"].key)}>
                    {dayNamesMap["კვირა"].name}
                  </h1>
                  <div
                    className={`${styles.week_day_text} ${
                      expandedDays.includes(dayNamesMap["კვირა"].key)
                        ? styles.expanded
                        : ""
                    }`}
                  >
                    <p>{formatTextWithRedTime(scheduleMap["კვირა"]?.text)}</p>
                    {scheduleMap["კვირა"]?.updated && (
                      <small className={styles.updated_date}>
                        განახლდა: {scheduleMap["კვირა"].updated}
                      </small>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.ornamentContainer}>
            <Image
              src={maturityIMG}
              alt="Maturity ornament"
              width={350}
              height={350}
              className={`${styles.ornamentImage} ${styles.maturityOrnament}`}
            />
          </div>
          <div className={styles.slideshow}>
            {images.map((image, index) => (
              <div
                key={index}
                className={`${styles.slide} ${
                  index === currentSlide ? styles.active : ""
                }`}
              >
                <div className={styles.slideImageWrapper}>
                  <Image
                    src={image}
                    alt={`header slide ${index + 1}`}
                    fill={true}
                    className={styles.centeredImage}
                    priority={index === 0}
                    quality={75}
                  />
                </div>
              </div>
            ))}
            <div className={styles.dotsContainer}>
              {images.map((_, index) => (
                <div
                  key={index}
                  className={`${styles.dot} ${
                    index === currentSlide ? styles.active : ""
                  }`}
                  onClick={() => goToSlide(index)}
                ></div>
              ))}
            </div>
          </div>
          <div className={styles.auditorium}>
            <div className={styles.auditorium_vineyard}></div>
            <div className={styles.auditorium_image}>
              <Image
                src={auditoriumIMG}
                alt="auditorium"
                width={580}
                height={585}
                loading="lazy"
                className={styles.rounded_image}
              />
            </div>
            <div className={styles.auditorium_desc}>
              <h1>{auditoriumInfo.title}</h1>
              <p>{auditoriumInfo.desc}</p>
            </div>
          </div>
          <div className={styles.ornamentContainer}>
            <Image
              src={iconByz}
              alt="Byzantine ornament"
              width={150}
              height={150}
              className={styles.ornamentImage}
            />
          </div>
          <div className={styles.sermonContainer}>
            {blogData.length > 0 && (
              <div className={styles.sermonBlock}>
                <h1>{blogData[0].title_post}</h1>
                <p>
                  {blogData[0].sermon_text.split(" ").slice(0, 100).join(" ")}
                  {blogData[0].sermon_text.split(" ").length > 100 && (
                    <>
                      {" ... "}
                      <a
                        href={`/sermon/${blogData[0].id}`}
                        className={styles.readMore}
                      >
                        კითხვის გაგრძელება
                      </a>
                    </>
                  )}
                </p>
              </div>
            )}
          </div>
          <div className={styles.videoContainer}>
            {videoData.map((video, index) => (
              <div key={index} className={styles.videoBlock}>
                <iframe
                  className={styles.videoFrame}
                  src={video.link_txt}
                  frameBorder="0"
                  loading="lazy"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                ></iframe>
                <p className={styles.videoDescription}>{video.desc_txt}</p>
              </div>
            ))}
          </div>
          <div className={styles.appDownloadContainer}>
            <a
              href="https://play.google.com/store/apps/details?id=geo.orthodox.calendar&hl=en"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.appDownloadLink}
            >
              <div className={styles.appDownloadImage}>
                <Image
                  src={calendarIMG}
                  alt="Orthodox Calendar App"
                  width={100}
                  height={100}
                />
              </div>
              <div className={styles.appDownloadContent}>
                <h1 className={styles.appDownloadTitle}>
                  საეკლესიო კალენდარი ანდროიდზე
                </h1>
                <p className={styles.appDownloadSubtitle}>
                  გადმოწერეთ აპლიკაცია
                </p>
              </div>
            </a>
          </div>
          <div className={styles.appsWrapper}>
            <div
              className={`${styles.appDownloadContainer} ${styles.androidApp}`}
            >
              <a
                href="https://play.google.com/store/apps/details?id=ge.sazu&hl=en"
                target="_blank"
                rel="noopener noreferrer"
                className={styles.appDownloadLink}
              >
                <div className={styles.appDownloadImage}>
                  <Image
                    src={sazuIMG}
                    alt="Sazu Patriarchate App on Android"
                    width={100}
                    height={100}
                  />
                </div>
                <div className={styles.appDownloadContent}>
                  <h1 className={styles.appDownloadTitle}>
                    საპატრიარქოს საზუ Android
                  </h1>
                  <p className={styles.appDownloadSubtitle}>
                    გადმოწერეთ აპლიკაცია ანდროიდზე.
                  </p>
                </div>
              </a>
            </div>
            <div className={`${styles.appDownloadContainer} ${styles.iosApp}`}>
              <a
                href="https://apps.apple.com/ph/app/sazu-patriarchate/id6504517690"
                target="_blank"
                rel="noopener noreferrer"
                className={styles.appDownloadLink}
              >
                <div className={styles.appDownloadImage}>
                  <Image
                    src={sazuIMG}
                    alt="Sazu Patriarchate App on iOS"
                    width={100}
                    height={100}
                  />
                </div>
                <div className={styles.appDownloadContent}>
                  <h1 className={styles.appDownloadTitle}>
                    საპატრიარქოს საზუ iOS
                  </h1>
                  <p className={styles.appDownloadSubtitle}>
                    გადმოწერეთ აპლიკაცია აიოსზე.
                  </p>
                </div>
              </a>
            </div>
          </div>
          <div className={styles.contact_container}>
            <div className={styles.contact_title}>
              <h1>საკონტაქტო ინფორმაცია</h1>
              <p>სატელეფონო კონტაქტი და ადგილმდებარეობა</p>
            </div>
            <div className={styles.sub_contact_container}>
              <div className={styles.sub_contact_img}>
                <Image
                  src={mapSameba}
                  alt="location map"
                  layout="fill"
                  objectFit="cover"
                />
              </div>
              <div className={styles.sub_contact_desc}>
                <div className={styles.contact_info_item}>
                  <span className={styles.contact_label}>
                    საკონტაქტო პირი: დეკანოზი გიორგი კალანდია:
                  </span>
                  <div className={styles.phone_number}>
                    <svg
                      className={styles.phone_icon}
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path>
                    </svg>
                    <span className={styles.contact_value}>555-725-709</span>
                  </div>
                </div>
                <div className={styles.contact_info_item}>
                  <span className={styles.contact_label}>მისამართი:</span>
                  <div className={styles.address_value}>
                    თბილისი, ავლაბარი, სამრეკლოს ქუჩა, ყოვლადწმინდა სამების
                    ლავრის ივერიის ღვთისმშობლის ტაძარი.
                  </div>
                </div>
                <div className={styles.sub_desc}>
                  <a
                    className={styles.btn_maps}
                    target="_blank"
                    rel="noopener noreferrer"
                    href="https://maps.app.goo.gl/WSd9qPDiV51P5C6s8"
                  >
                    <span className={styles.google_G}>G</span>
                    <span className={styles.google_O1}>O</span>
                    <span className={styles.google_O2}>O</span>
                    <span className={styles.google_G}>G</span>
                    <span className={styles.google_L}>L</span>
                    <span className={styles.google_E}>E</span> 
                    <span className={styles.maps_M}>M</span>
                    <span className={styles.maps_A}>A</span>
                    <span className={styles.maps_P}>P</span>
                    <span className={styles.maps_S}>S</span>
                  </a>
                  <a
                    className={styles.btn_facebook}
                    href="https://www.facebook.com/deafparish"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    FACEBOOK
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  function formatUpdateDate(dateString) {
    if (!dateString) return null;
    const date = new Date(dateString);
    return date.toLocaleDateString("ka-GE", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  }
  try {
    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";
    const response = await fetch(`${baseUrl}/api/main_database`);
    const result = await response.json();
    if (!response.ok || result.error) {
      throw new Error(
        result.error || `API request failed with status: ${response.status}`
      );
    }

    const processedScheduleData = result.data?.scheduleData.map((day) => ({
      ...day,
      updated_formatted: formatUpdateDate(day.updated_at),
    }));

    return {
      props: {
        data: {
          scheduleData: processedScheduleData || [],
          auditoriumData: result.data?.auditoriumData || [],
          videoData: result.data?.videoData || [],
          blogData: result.data?.blogData || [],
        },
      },
    };
  } catch (error) {
    console.error("Error in getServerSideProps (Home):", error.message);
    return {
      props: {
        data: {
          scheduleData: [],
          auditoriumData: [],
          videoData: [],
          blogData: [],
        },
      },
    };
  }
}
